apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: dev
  labels:
    app: nongkai
  name: nongkai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nongkai
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nongkai
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
